version: "3"
services:
  karmen:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
      HOSTNAME: "${HOSTNAME}"
    hostname: karmen
    image: jrcichra/karmen
    restart: always
    volumes:
      - "${PWD}/example_config.yml:/config.yml"
    build: ./karmen
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
      HOSTNAME: "${HOSTNAME}"
    hostname: gpio
    restart: always
    image: jrcichra/smartcar_gpio
    depends_on:
      - karmen
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    privileged: true
    depends_on:
      - karmen
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: jrcichra/smartcar_transfer
    volumes:
      - "${PWD}/recordings:/recordings"
      - "${PWD}/settings.yml:/settings.yml"
    depends_on:
      - karmen
  nas:
    restart: always
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: nas
    image: rastasheep/ubuntu-sshd
    volumes:
      - "${PWD}/nas:/recordings"