events:
    python1.event1:
        - serial:
                - python.action1
                - python.action2
    python1.event2:
        - parallel:
            - python.action1
            - python.action2
    go.e1:
        - serial:
            - go.a1:
                - akey: inyaml