version: "3"
services:
  karmen:
    environment:
      TZ: "America/New_York"
    hostname: karmen
    image: jrcichra/karmen:ci
    volumes:
      - "${PWD}/ci_config.yml:/config.yml"
  python:
    environment:
      TZ: "America/New_York"
    hostname: python
    build: ./python1
    image: jrcichra/python1:ci
    depends_on:
      - karmen
  go:
    environment:
      TZ: "America/New_York"
    hostname: go
    build: ./go1
    image: jrcichra/go1:ci
    depends_on:
      - karmen
    ports:
      - 6060:6060
  node:
    environment:
      TZ: "America/New_York"
    hostname: node
    build: ./node1
    image: jrcichra/node1:ci
    depends_on:
      - karmen
