version: "3"
services:
  karmen:
    environment:
      TZ: "America/New_York"
    hostname: karmen
    image: jrcichra/karmen:ci
    volumes:
      - "${PWD}/ci_config.yml:/config.yml"
  python1:
    environment:
        TZ: "America/New_York"
    hostname: python1
    image: jrcichra/python1:ci