name: Karmen
on:  
  push:
    branches:
    - master
  pull_request:
    branches:
    - master  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build & Push Karmen
      run: |
        bash -x ci/ci.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_USERNAME: ${{ secrets.INFLUX_USERNAME }}
        INFLUX_PASSWORD: ${{ secrets.INFLUX_PASSWORD }}
        